install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-development
  on:
    branch: development
env:
  global:
  - secure: LUcXEhV7/Y1wHJGuLpxrbWj7rukwSjtQjrvc+LLdpWLuFRulPpeCwvCFp4f5ZmKrbwcaxCKPX0WStGCQm25UJGSjFdCHVIEL6jcJyaJqgrzM9VwwSgKlT8egVTlodDxzwO14MLA2r4rWWJ5ik8oRVWONPCVrDgjTNZSj/8vxOKjURxpn0TLt9M11H6wsK3DRCt2vPGiDcinq/00HL+km3YGWSEDKLtpzZg0tIMUOXFE7ANx7V9NS2HNrYEjzHNy/ihSjjEhyOElSxModVkt1/wIrfWKeUegfiJu7DHUbPsglQxbtkWUqrOjW1iV08QfXg9oEIxrDCdToTw3SLIq/zijxCpFo5pmOnVg3NpWBpBfONEGzNazt8gznwvFMLPyHq1l32A7nCmTqPZBsOYr+Tx8SF3e/7YFsNwccbfTSDCM7oopdRMRLveQb4le5/vi30N+og6kCKVJ0Byutf9cYubqveWndVIA6uAFV6W26LB8QBkJBEL6Ut2V9WqhjIHN2i02KUPcMM/+dMdZLOD7UHUUvrDXv/+uFSGVHweAuP1WMaG5pI2DB29wXH0/GEHCltpwVRvrOKcMhNzmi7HtLmYJt2IBk8gyMyP5X5X3+z+CnP5NMrMHKjRl1nJL4d1AHewQnDFe/X7SwS9q0vh0BKK0tEq+RbAA00KcGoTy5QMU=
  - secure: DrpsXWCauY4TCdLu39zNODm/9lfVcKNOafMprMxm2aySpOpXx+rmeFzAModuJ+Sv8KOTg5FND1OcY5f95fJEBkaWbG04C12W7vYN5Nkv5UPc3UXkT8VstU4bfihOS+DtK9bdn5sCtyJ/9bw8ajtJTF8M9Wspu5u9X/qC1GG9e8hY70DokjObo8oUXRQ856Wmo8T/eNtlWtC7Oz1krazJ9eQIMHglpu4MwPXD1p5qGfzaQvmXWqNc+scTkfgJApe8rlGDTMcwsx3o0TzQdCAyNFBhFgQfjC/307lSi19rmaYm8n4ZH/uDIWsTsE143zh1ls2H3SSW0LY2CXz/i7oqpZuYL7tt9yuQeHywZROjeJdu2RWUcvRqEsid35N15cYdDpcjbDHZQV8O99jr+K2yEJlYNKHuegranCZ2Acgo990/Nzm8N6HiYnu5GEj7x3IQ25JXXvKxPyZxWsFjvbOM7akgjcTqNdL+ZHL6XijlEDb+/C/PQLVRmE9c1fg+59fiTmypUEz0jaZiaUFb6H6mJosAaySXk8NfASotxOKPGpVBGZj68a07WWIg/E7gLsLWLXof9PER8puAQOyS7fY8rTcZSAT4zTYf1mTtmIAb2d/0vfnmbd63mcurfpsCjWc9ONPlCa6Jcg58w9y33lSv177Bd3HLdbNoO40PQrbYzvs=
