language: node_js
node_js:
- '6'
script: npm test
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-development
  on:
    branch: set-up-lambda
env:
  global:
  - secure: xIiLguRdb70PzjeAINRZk/RFIOBiGvR4dFHCjsfuz5ImO1MvJ64PgWmNK/vOrjgM65i705zpkAhKij0QeK0JQOtdeVnS55e2o6hhKZft6dforR2KMYUgZ0E/6X1PmfeYwKanR5XWh9QFJK1+nshZTBimm3uOfmHevpedxa7mO83kbdzW7zEgm0rP0kcOshq0s9vthzeFBJb2+kn8BkQoa4BmyHtWSr2s0EG4u5DFRFskxW7B7eza87RvqxMPEFCuvQLqeQHJ5EedHfco3671wg/fLq7KoyUY7w749n4YiHhbzkzpe/R1zi39mV28kV7zi+kmRKqmqr1HqUv8mlEnIi9asbsqA+XMD/Q8BT1GUsy/sUMggnUEU+MXoV63IGaMAJkkSzEntbNBgCurT17NKfvBllo5JcqZQ7UrHROP3ZAtICl8+Dau2AycBOrxfoRTnKfNxRgmqo+d96f375/nXEttmdg6K1tV3wSl92xzlXCALpSomSYBP4jmSXzMcqlXQ7dEZu80r25RjED1oWOh5ylztyyXCTHg0ZYAjCVV6VYX/hA8twW8P3K8uTMVc9AFondubyHfI42x2Fi5mNxGLZZqe25O/IlSsTj3389AVbTfa5g07JTnwChscFUCVn7RlAEw8Av4f67KtAuyglj2P8Ut2VIXL9zIlFTUCnv2Xoo=
  - secure: zLKG4/Ztnhi7eu/7WNd8hIw45vIgf9wIhrxDXglAnn6qTUdASpU1dWCy8j1eKRIRZXSNUQ1AaXBjDSpCHwCLP5MkD28T6++pBqStLc6J7ldZ7zUp18VCjKUK91rwj/RTVTGZHrN0wHNOuArqbKq+YAnU9SVwbdGp6pRkKz5ZFw3zETKrifZNWNkgC5TMJ5m7+6pNUyPEsf/hN/sznlayhxlEnG2D2U+cWZZcwm/1PzCVpNKWA1WWu6BNjlHp3NckWe7bz89DbQFhiyoGa36525urJNZGMSGLTwb6Efh6dPp2cWFf7ZaKtbTwIfgi+OAS85m08Z1VXIrYmoKYRbD4B6ESqY07k+GphEI3/VrqjzIi/hjelQA6s2lZyEZBq7zlIPaa/MiiXlmFjd3FoedZ44vbNN/17GyKwZwC+8m5VGDqDc9NpNdoSB0d7nyZo83EXGPMW5M++dZj4wXqHZBWCp/Yv3hBqkt+pzQy60bwjJ9TzvQ0+SBMiJpPDVZ+DpI/bZuP5L6jACMikaCbw7dFLlhe8q7cIYlQr1h/6OS5n1NJkWDZarJ53y4oIIUWQGjSNReApAlYYkjZTAEz2iGJUMJgwmy/pXbxtqGRaYVWA8ZhE3P5i79y6HhpxRJxAgCZPfO4WM7KamDHn53GREbJY7WHqKXT/OJEFmWcp1RUdUs=
