language: node_js
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-development
  on:
    branch: set-up-lambda
env:
  global:
  - secure: PdtHxMQccfpmSOyY1nifyonbSxSU9c3A5l5o4wXp4DbqkEv2A1JIUvTkL0a1wgV4f+mo08AN8fCnSzlX13uEMPBh/u2+4o171xT7sDiw0M5n0+aQ66R1+4uINDf+6DLNjGpOf89Pto7DyZvXsFf9qGYLAFk1zgZN4y97/xGnBSftCNkM4g9GadwqPyyyYCOMxz1UsX/zfWoo8QjbElNYrSHcWLBa+GE5psruqAAy4K+gYv7SckzeYIjO3to7NmHL+IqwvMOw/1GdCaxN/xue0+Fsy5jHjRbK0NZQyzFNfJbQ5fNBOxVWq/vc9LI60GO4JFTQvKQESO6pGCtqzpyfIjjOvUa5CuqxbX4llLFAwhQc34jZIYr/3xxvRmqFpN8i0yJCSJxjhnOPblbjS7eCnPWc4fsKs8QOgkWYLpCjFRX8JPO81xfoa0b+aLa36l0a2WOzBPt+YUpASnyXx8moSB1c2N8x5cLOu3YDW50uY1i4L+cfjpaZHqX59iSs7qTc+f9t6cH4DJTtfUFJmxPVu6T26OPSoFi9P1cOVBxkqEHN5QJcsI4AMChp1725CeOp+Z7dRcJjJEiDYck6Wj20m8qoZ5RCerf9viEL1xswEe+RdcC7jN9PrkIPlYP5T2jRJV3/lRyOlgRWsrW89GrN2FJRfDYDP5gO8V5eOHuYRAQ=
