language: node_js
node_js:
- '6'
script: npm test
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-development
  on:
    branch: set-up-lambda
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-qa
  on:
    branch: qa
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-production
  on:
    branch: master
env:
  global:
  - secure: Rx1M/LV7aloabM9Dg/3ZCOsaw0zFVaM3BfAf5PY+6U5y0ujonOt13B7YKzJR/qjfYSlGmDXbI+eFYvFNexAqHje74R8ydFLHPbeaIOxVajEvrH+6ksun/YhDuPiNv04YqOEoOJQsuIEY2olhsqKRLSa+PVJxL4TSEd0/NlSwhZGQkk6rzTpX+IdUN9sbEa0ZKTzMIA+04FQ9a5RlQwTf58Tuo5qJ9AuB2k/3vgq3SOVnKcZsemya+jVka4hbm3HJsIy3616t/KnRltuwyvEKyay/wNiYSrzs72SbXTVl7jnFd2VhNY99o1GYb9tju0BZ7ya1rx5tipqfBXBywsdMKm7J7+KQAnFsLOdxL7ne/2zkVF9XPbofW2foLDnwqhOQAZiRUInSla928Sngrbd1xeylbyFj3BMPXlsvOakJVQuNWtu8YpZICYci4zaJYz+LksbqrUsk4q9WRudTuxSYeGRXHEziFNmMPPQYkLE9Ao1Ooc4MEauMsFK6TRjNwES7lLZ1TIQ3IpkO28mHA0V+7fsSLYa+588BAlXdyujsEugNduo50I9CkuRk4XC10CIJo+i4L3uOY4yIZVClxZgBLRdr9gNyh+pTjYwU3nMWK55o6vlHc9FKCCq3oh1Q1vhR1zBu6/nvKqVbGcdCqT1/vH0nxBvwHTT7h5013/2lHuA=
  - secure: 4EpruB9xJ5kkue4wLsa5v3zjivHr8m8ZaPBN+DtxX9p0mokZqH0ilXU6niK3OAMiqCfxiOsfd6440rA1/Yf9HqVHejsWg/d4XHrzQHu2Gx/2pELJ9ogCtuUg4lpVTSa88JP4VC75oED81Vv/2BgG9UmgFO8Wq+dH2jUqGHSdtLLjREX/53aLKaZKP/9Kb/p3+zEthvoM6x/Btjqywbt8IAGLvg/Rs1Xi29FPqVJdPy5Y6E12YAH9AB9bVS8UQySiYRPy0D4So0Ag8LQ2VC/R00O7VBoZ8p6JHnxbMj8eYTqc3uTqJYIb9DiY3b3hjmU9HwfO5oGH6Fxu6E/FIHqe5pIACtRq0lmnu/r8tbdFmbIJ0HYEUm7aqYFuENOVAUFVzN+Q2sadPjL+mBfDSfeFYIB0X+QQ2BWk35ffEzKJnuztJOyR8ZDqRcYmizHu0DdrqSLo+kZKH6nyO9trHYJjGByu98+LAcBtmxT0VTTCnVNSqlDQMykGL5aNm/M1BI2BNOFo852rd9jTIH42tQjNlTah7ma9uOdShU/45e0Jnw9Dl12XBiBI4bbbeb6xe/DbHhr6bWT7p8/9nb1uG2t9XD4dLaAsXJ8uSqrasZEihctt6cbo38JqyFkfeM9SQxoTLJbQqL8R1GRa6ziN44I7UGK4jwMbNyInDAGxH4USDg4=
  - secure: uZCcZoOIfxuhA0OeLVHxRLT9JCL6g6f+XSwXHc/V0lOyTtroI59iMZboctU65BxUKtDrWSmV6VrUuJKzUk3F+TEb799d020RWLTFj0Nl0x7b0gZD7FXtkjq/j21or6yzxrK4xEESUk8iU6rR5zfy5pr1psKwAz6YmiuNA7IDyZ0pYB99Gch14Jck5Xfg6yN0PV2zeG5A8jIMsuh54WG/emfWBDkrKlVcMxqszCGZMbFwufjA0S6ZhHYQCdnqMS3E9KnlwMSerzaLh8E+6II8PFK6QILilhPho63lgfjaHSkulzWSE17xVCbipl0hmSKTHiJ3+9OPQnocOJ3lQ+sn3yQ57djwhHcPzcBKvkuRndT49hX6ZaaDnF8nQY0LiCBN1Ue1IrRBmmpApEYXkIjyS86FnJ8F2d/YQWrte0BZZtaGrzteCM7X8RyrCyXi7892gFykXmDY+iioVQHewpKsmarjvg4frpHvTV0nqRW05k0wuOR+biso2qvFNbrO1c6i36nu+1Yq+dRH2iTcEy+E0ynXXYHHfWM4E7Lo8zOQwzVjoU7cshpEkCs2mpKtlO7VeluGuDeoyUQ3dt1f0Y4Miu/KgTUJGvx9DBvYFeGv2U1gA4h8cEHysL0Ft5WMFXsQ8F4l9kj1jKPxRlrf3/IBvhmFrrDkGXX4+vXaJawrDHA=
