language: node_js
node_js:
- '6'
script: npm test
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-development
  on:
    branch: set-up-lambda
env:
  global:
    secure: uk/b7c17snMjxhX+w3uJtXMP/Z8Lg6j2uPUjo5DyeU2rnmagOJgywfzT5wlwIbK3FL1dMBS2xKJqSm+COx/tYGG7JttkiLwuV4FzAPu5NbdVCwyqhX0zREzBN9GHHL/EcsN3UFONEEWraCrFWtnnNezcJ9j4rej4vR+PESgP1sYZjPxYW1s6V7evfnf2FpabMbMzZJV2G2sGNCQbpdOkn1V1w2LSQJjm5iSheEMzAVrSc6BWf2PMrX7rbMzpZYtxNnQ3J6XKvCFX+W88c9RfbzulxGWZlSs1Xe6VzfW057SPwNCrXsUfKgmkM1PP5v56O6tDRyBR8k5BM4dA4tB0nyVD+BW1gLElP1ApfEN9D47D1X61QFPyOLRVpkPQ7eZ6udscI+uGZs/qBRHzVH8LrZKGyFm4MkLVMhhsysRRyIw/vQw21FGLDHaEvXgzkT7dpz98+aBRYZMf4ynbAgKDK4t1bzBTz1WmOYF4ZfVxqcLD8a2jf/Gga+IkAjYiIeJKfdpcHgD0qEpRbpWuvduGuyfSrJme1IyGE1xuhMj5Lm/JwEa4fjYomx9vRRkWsQFVp9oABEy5AZFRrtOJBT/57wb6raNgLPdiF7Q69r2GMdUHBnGXwWLRXMZtaeahz/rb97QLJaJeh55VB615FHVgyy6405inm6vug4LGI3VqQno=
