language: node_js
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  script: npm run deploy-bib-development
  on:
    branch: set-up-lambda
env:
  global:
    secure: c5CcJxIyT0b+jFdiprNTm+fQWkfSiX8HTZAcb4ns3oAtyWwS3wAHR4EpV9gNtOo6Vyhow2WXwRziqUO4LG8foSP6uLqwrzjORTFdtmkqvN3V10sWSuRks92cmfQbBYIMh+O8taMOlDx2wfc01OwKTNG+Nrj4wGDfhKIkX16iNHGg2ijHmVeUx565/bXuftF/uHXOoMs4QBOX/hLdIKIvH8AIFubhBNMnVxObKhI2kxbf6/AlknCoCJGwqV2ffjuVC7tbNFNDqrFqpPeDra2p6w5ZpSeUzKi3pSRjZcMndjZHQ4fDbaQUXzHJBL8dECgIIv+OCnGCaYXrPs4jdYMgZ+HL2TctLJdEOaFFXGAfOSd9dekvOFkdelH/3rsxfxorJtRggGXAXpOQlRqjKwGIwdP0Hk+40hTsrSsc1BuikBCTm6c4bXQEqEHskB5CdN+dc/pTajI9xkQR2WyRq4gRUpVyqaTgj9m2A7QwcRBvYywTICHIZ0G8Qfz8tnI2YS+h7jHPnjJdtgIROa1BIVFqVbka9qq1BZHG6H6rHiwyssLVMH4GfiAQq/TyM8VcbVrhJ2zcmQRZWK3isi0eArjdW2ZQOFTiaUgdWEDeSBaEag18MXD+Zarmel7RUwvHrCEJAMMhcCTAoOijrCGcp26JOPvjDCbkgD67xBEj2c9gqUY=
