language: node_js
node_js:
- '6'
script: npm test
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-development
  on:
    branch: set-up-lambda
env:
  global:
    secure: g6z1CU7Y5TEdTe+TAnrubzSAQahI36DiJU84wGODiM8GPQKUnBfvTV6KbgKaFU6fNijl4kP2vzcKgNXS+l6rHX5tmVra/M2VoInmlecZm6QJsElJwqWYSSkTv8ChnxrRi0Yk1AfacgbPd9o2kq/3rVl5MqZhOkOQIij5uyPEt/xAPFpr2Wmj2Kk6Fv2X6smI0abR1erU5U+a7I2/M30QAkx+c6MAr4Zw2wWCPAuGrEF/uUiRG95+kKOQcv+XCR54cKVu42Bg1WirM6FI5rFl22Bmhd8XaogePc3vgVTHLdXguRNaYMP+LFtaowraVgIQWnCfoMBP2WlG1BxckvcfAmk+JFPCRC0bDk5M7UaqWY3mbdal5J5VwZgGIb/tNkM3clfeMBAl2FlXPYy9y4QsxC8LvuThZKPcZKK1RXeGce3FuQJ18+JoiN4ptz/2kVL4H7297LIW/VdHVbEzVbzwoPwprWUIT0n1nl9rnWrKCGe0DIXt0c/UqTf/bLl5galdPFqeeNQHqK6Zyfl9k00isKPwZ2bocldkKq1X1e+yh76olhW/WCw40PJvYbNVfkY3WKzGVyXFjGe9+8rT/bbhfwvWY/IZA1vedDZUnBFFYhh5SQr6VfkWLGtrnPlspyjDzfbLEZi6EJyFUq96iaLTAlip4vNdMLU9ryECWkljKl0=
