language: node_js
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  script: npm run deploy-bib-development
  on:
    branch: set-up-lambda
env:
  global:
  - secure: q2QRKA8GWqIW5Ih4EjuLdoGt83PPJD4mJ+UsyTZ8tagbeS8QByKh1SrgNG7fVjjyk2RbCravaHKOWn7+W4nz4H6iKDmQEdG6HEM2Gnjv7AoHQEVhU+8FzkqSX1YwYYYzLzazTnJvPpw+V5jmR6Ew72SGEZdBqVrxUTwBYqAURav0VqXzyEkRzv/N5T/agTfdyhVeBQoomQuS5iFkWBzj/uLeW/XqEU2jXC55cYsGU/yFBBg7JMKJL0/E1NXAPZFKwmQbQLI7RXGXgsFtzHLoU/cRSOZeQDaovPw08BiviJQazpLE6TcnnU666shnj1Bk9BcTlTFWfhYsGmPK4LzObZVlimPHGsa71sPMtAJzE15CVzgVIlKllQb34DjnxeXTvbFemsvu7jsJV/hvM16fZpMilrD3nkgUHgbxwqE324Yt9SI7k4ErGHhwQsMMY7fZvu6kpRBblYwPNQ+2OQNCfQuaAkR0E10BpACBM3STYYlyxqnbXn7la8XNB3uAQO9AzX8NxcUYQX+s7tpSPvvLOLqNSWxwUnJuYJc2OgDSZ4i/Mcess8Lis9++pP6kJ8fxPFUyQ+HabBmWPCNVstg64Yxlelck9gtJj6SIyRMYoOinbwkuiIyfFcmTk9dWhJh4XJeIsA6kQ9y8ZFPCbke4WBU+yBy7ASSORmb5IZFqua4=
  - secure: GWU7/SMmGe7Z4okSJgSTNbVubnv4PDFbX39kHaeJW0dUp5eCJrSuQ9fTSgNILNQjKrRr0OhofDgo+Oap5zo5QgzyuuAG6pi+epNU0hlSkKWHhXHLWQF5O6jIXkHvOW3u+Nfl/Sbyv4kS1l2os8bGbq8AMjCYxE1SCVEIT+SjPz+9+5tJAALFYm5QeT/KoL1jyYYE87Tx/HYexfG5VML1+RETsISA5DL5C8UXE637PA+iVpvIqX+M+rGLaqUQFxnFT/rSi1/sFDE8+TXan6jcoWi0LPaUriM5TooDccDdsjrNwlyWw+mGmOtUkN1KsCWPYsuR6WZmjeqSfKusGS3zmuFRCzl85WkIRGYs8R7vmM42610YFsSz9ZtsRRX+792YmVGDyv4ErbywYsfSgBeHUegaLHp9vhqaye9h1GmUvkY8sBExkbEcV0aLIZHhlazN6j/DswzrN8ZKa6yydZL+og6fK9x6R/5iYZmEpjGahWYLGBnbsVY+07GbTCQh5sKdEGSIPnzB6C8Acg20MYPozcCG4Q2uIWLGY2nlmiXHGg9psaTPU922PnWGa4JpJ4M87c35dIvmiXmwCK7z8MYZ7gfkUCRuZGlu2/oYzmRA/RoBlj3lAv156u9RgbBsj6AC9MLNt2NzeGZ41/TLpyki3UFR+j+U6cummOK5CgYH+cc=
