language: node_js
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  script: npm run deploy-bib-development
  on:
    branch: set-up-lambda
env:
  global:
  - secure: q2QRKA8GWqIW5Ih4EjuLdoGt83PPJD4mJ+UsyTZ8tagbeS8QByKh1SrgNG7fVjjyk2RbCravaHKOWn7+W4nz4H6iKDmQEdG6HEM2Gnjv7AoHQEVhU+8FzkqSX1YwYYYzLzazTnJvPpw+V5jmR6Ew72SGEZdBqVrxUTwBYqAURav0VqXzyEkRzv/N5T/agTfdyhVeBQoomQuS5iFkWBzj/uLeW/XqEU2jXC55cYsGU/yFBBg7JMKJL0/E1NXAPZFKwmQbQLI7RXGXgsFtzHLoU/cRSOZeQDaovPw08BiviJQazpLE6TcnnU666shnj1Bk9BcTlTFWfhYsGmPK4LzObZVlimPHGsa71sPMtAJzE15CVzgVIlKllQb34DjnxeXTvbFemsvu7jsJV/hvM16fZpMilrD3nkgUHgbxwqE324Yt9SI7k4ErGHhwQsMMY7fZvu6kpRBblYwPNQ+2OQNCfQuaAkR0E10BpACBM3STYYlyxqnbXn7la8XNB3uAQO9AzX8NxcUYQX+s7tpSPvvLOLqNSWxwUnJuYJc2OgDSZ4i/Mcess8Lis9++pP6kJ8fxPFUyQ+HabBmWPCNVstg64Yxlelck9gtJj6SIyRMYoOinbwkuiIyfFcmTk9dWhJh4XJeIsA6kQ9y8ZFPCbke4WBU+yBy7ASSORmb5IZFqua4=
