language: node_js
node_js:
- '6'
script: npm test
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-development
  on:
    branch: set-up-lambda
env:
  global:
  - secure: ksLXD1Xa6SniXBqFJnfWQ1DaOdA8jNTqQEBtHqGW1l6GRLXlILMKTdqJjaLZ4HNJ7nMEAQO+6QY/MoENQ+xHQ+FfRj6O55JzrP1ct7l7X+bz3i0l/U0LdLfobhisBpCnTUH4kQ4ToZRN0GGcoKeqorUYbET5X6F3Fh2TIVr4ZoWCvjmMel2w0K/PGCwuj1AVH0IVfkMQ2ndYMH+s+o6dkhYqWNUWYLngldH2NAXVfALoY2A5Nek+HOJquP0OXGzm/JwK6SSzQIJHYq6jQS5HjBHumW+IoCHlt39hZ6dExAwshSzglbKZ25Doh/Vr8Nrm2T1L6i5sMqQqjdxaGz/67jqlpKQCAqx+svOMbPjDj6Q/LQ8Pi+o+sL0DVvtVKHx75HhCvllHOTB5zfkhqNMoSrvEfHOndkT9wTd1AfFwzw9TaB9PrhqvQxHy3ZLKOu+1qyaqWjjQzahgNAr2wzzwZFGOs1EL6ySdpseW5heKlf77rv1eG5qWLSvQR1nk5J0pKKUXaPrzMjmu0zk9nPk0X7gsY/mykIP8JSsRYyDoiOOK6YRRKdEm4EQpLNl6hB9HWL3zRtFN7COIq4b3J/qcB4iFd6vpRgx29GebzkMwYNJxaSwd2Trf/fra08NueSXhZgpM3pShnSuP6rm8bPBDhx9ABpUGoGev/tTTX+zRLjI=
  - secure: tI3FVjnbkEBwZbf5P496asiw+vXgfc2itJYLacoxU7TDS4BD+TgccGyyhLfVkPoLneh0lZpKczNi1dxC2EpW8N7ULjibsov4ORxQ2+O+WR55mZJJBHu7PCNU7CbFfvqJfeXf++7jnyQCO+RJEWXWT1+UAk4L5b3nQ+CVpfqjEeuataiOxdXYiYxWTzJeP2y1KxGe54ciJ4Mc8GIUG76xwhVRaMIDBBnXV0Q7ZXpX0qjHoU7aGWooXqNHiwDKbxhSxu+R6BMDOST86zGZt3Dk7fT6Ay1jLJjlutD4ZobsD8s5xq/f/EG5IEzpiNL6YECyZCqKM9Ih+Lk1V50gQbIfIENja7SzfAiFo5/ToSl0uTSMhVfMSDk9J8LOl5ndOJW5M5VTADjH2EEx0KFKNX7TslppNrdz27jMu3YthARLh/4Hd0lRGjNnhT5Iqv4u3UdjIDYopYGjGvwT8SyZ4QVEWt/8V5ZUVsIKQAhTWTMAWoe0w3HNHnNg+/WrZdC1fUDhCj9w/Hbg8lvm+h2Mc9K5jPyACI54iPogtCIosBphV2PN2FbyKC6LfuTKBreAWd0RlErwLT5GV+mz7WB/GS4sc8c9KuOH2tQDYuRM6u7RAEKfxiTvwWPizEUhzAOllHGBB1WQVsz5ciEIsqJyOJXl5est7nqzidPqCKNLhCKvZJ8=
