language: node_js
node_js:
- '6'
script: npm test
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-development
  on:
    branch: set-up-lambda
env:
  global:
    secure: TIy5CYi2oUGnlus9nhr/4ImA82XCd+hLR7m8+5y5KtRvBrl2T5rjNoeZZTMqit2zojLQcNVaA498CIKEOtI0kUyAo9bdIcgHBhz6p6xXFfIkSgI0y0yt8FPrn8DF5TdDxvXmkCYG9vxEBXij/2x4dItpM2rsGH7Kgx2TPnLmCpCwL3No69CaGEwRP7MvLrXK2XUym5sG+Gd7c1h5oUkeMqNDIXub+d7bclVECj2Cjbcx3QeWpkfDrI/x6QA7DoXhGUd4vmBECUVk4PINPrlHSi8uzMnjbIg/ApoIpqcqznKzap8awsqCnhZFa/pR/axtfAZgGsM+x0HEetMV90DP6xoYrfPGX9xDjVo3853VACybwZUQU58CGMPikjM0anVA6ij069LE0aJr1cuLgKwwVaPzrvoiH4zHmzwmUcxzejor28DGZZ0vgGfKTD0SCP6r9RNUkKeF0bUgydQE+m0+CYy2MC5JAu502vgYXkHzUxEKy4cMjIrWD2PSptYioEALMLGB7CYwPQhAmmtQMmKzxFbUXpqqL4YYQCFL2uRmF2BvNjfD3pTIjVgvC9Ex4kGnWEnznnFPQ9OdvUXZD4SKKnEjTNKZ3Fz/UPwcKYMw/yrhDHxa37ZQZh2INZNQRubHJzwD99raBFjSSiGBV8lid51BAkgaCqv3pMgmCsEk71A=
