language: node_js
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  script: npm run deploy-bib-development
  on:
    branch: set-up-lambda
env:
  global:
    secure: TAyJBTkFMnnOseWj2OSNa2g5SAqhqoJqh68GjO6eXGGY2TVwGYfhOmFnPRFT9k3sr63GvZWjuNGarIPtiHpbdAf2RoUTWFrWskFv7SUXS0XTpgXjE6qWwvvp0cnLe1jD/qp42nHZd1JAU9S3piEXrnTs81CR+Ky/EFzZBZXY2r7Eg3XpHfP987I45bbctbjMmLKziVlgNmrJruqQeKdHocVR2d1zmz+eMSi2hoRxkNkm0ttaZfHV5tkukSGq2kkL4EYjyX/oGyuJ1gRtPEij12ddCqw1ThAVwXXs/W39Tg5mnV4JP5TuxdrIgJqkkfqSxbqmaBwAr+jQvBczm9ax6fkYzUOaRg2j4+O4Zb5bGnG2+x5YZrG5LMH+lIMP987r+fhetIEU5zA21ssciXZgo1YdkhAqmLDVqgCQom2nzp5dK3MfLiMb1IfA+Gmk5+S1WMgqjfTiT9eXRDbgI6BI2CTj/CSfNYJZHma43+lvfiOYyXcj0S10zvZgy6QCxUlm12RhxruBO3bTlrXG65kDBobD0QojWSoPcSAJrQbWiIu5rDwMKoA4Zh9M2rJvL0Vih44mFeynGf+F7aKRbYiwQVkkHSTBCl/q0wXh9aTtIjul1wgLLzC79GtDvOpItQgEtG8RSTZVfntMLEknzBbbOw+GIGp2xq9bxRPjDvP0nOw=
