language: node_js
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  script: npm run deploy-bib-development
  on:
    branch: set-up-lambda
env:
  global:
    secure: RUjD9BBtwkVPDtiaPa6PCKD4+JUdAKMDyvIngOuoPcV5IJJGJEAccra0xTkQ+pTzNP2TOXt2wZmteJAf3CLcMP2rNtSZA56XRaPlvAMlwa8S3kENR9FRAgDZrX06NmkfYsHy5wjHk56Ypwdr1zx4Xr5/E+KZlIFPFwhP1bRl8aiPK529SK80ScwhrSk8742K0lNf4/Ci4BhcJa+Rc8WfNCdeCSEWIeAVd4iS1PbiMPWMhQVtJvvYpJXNCKX5UqOddy/W15898yJ3XPN7FbCA9P8Kq/KaW5aKnzmNNXBjVB+HTD62FVAGUUQDoIS/MXKgqChcJ1HLcNSGhEgVm1tOkhxeSfgdjpBS6VuX84+kUSkbLR/FAiq9WD+rAYSoiqisWki8PqkQfDkTrwRersDFEkodKXnXca7+55SVSI7jguU6SsZh4+vtw1UgjH9ovualYLNH7v/oXPQ8GgzXpUfVk8wN3wkYkA6cz6BBeLWphdEbXB5rvaM1jiJpbgx8unM25h4jhor0SmW7iRx7rBFxc2rXWsXXE8HAKU/hFat2O6qH5m/wlP9mhP5TR+9msSSoFxq0ixeDGuVD0gupVJ4PoLlqL1ADAzx6WLZ4qxQDLk8UCthE9+vOqVy+gXHSB7ulRBVeepwbPLgXbxJf5+Rp13f72tJqNRk+fXHkBht9bAw=
